{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smithd.secretName" . }}
  labels:
    {{- include "smithd.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.secrets.apiKeys | quote }}
  aws-access-key-id: {{ .Values.secrets.aws.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws.secretAccessKey | quote }}
  gitops-ssh-key: {{ .Values.secrets.gitopsSshKey | quote }}
  {{- if .Values.secrets.slack.webhookUrl }}
  slack-webhook-url: {{ .Values.secrets.slack.webhookUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.flux.webhookUrl }}
  flux-webhook-url: {{ .Values.secrets.flux.webhookUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.flux.webhookToken }}
  flux-webhook-token: {{ .Values.secrets.flux.webhookToken | quote }}
  {{- end }}
  {{- if .Values.secrets.nats.url }}
  nats-url: {{ .Values.secrets.nats.url | quote }}
  {{- end }}
{{- end }}
