version: 2

project_name: deploysmith

before:
  hooks:
    - go mod tidy

builds:
  # smithd - Server component (CGO required for SQLite)
  # Only build for linux/amd64 due to CGO cross-compilation complexity
  # Use Docker images for other platforms
  - id: smithd
    main: ./cmd/smithd
    binary: smithd
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

  # forge - CI tool
  - id: forge
    main: ./cmd/forge
    binary: forge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sorenmh/deploysmith/internal/forge/cmd.Version={{.Version}}
      - -X github.com/sorenmh/deploysmith/internal/forge/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/sorenmh/deploysmith/internal/forge/cmd.BuildTime={{.Date}}

  # smithctl - CLI tool
  - id: smithctl
    main: ./cmd/smithctl
    binary: smithctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sorenmh/deploysmith/internal/smithctl/cmd.Version={{.Version}}
      - -X github.com/sorenmh/deploysmith/internal/smithctl/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/sorenmh/deploysmith/internal/smithctl/cmd.BuildTime={{.Date}}

archives:
  - id: smithd
    builds:
      - smithd
    name_template: "smithd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

  - id: forge
    builds:
      - forge
    name_template: "forge_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/specs/forge-spec.md

  - id: smithctl
    builds:
      - smithctl
    name_template: "smithctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/specs/smithctl-spec.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Others'
      order: 999

release:
  github:
    owner: sorenmh
    name: deploysmith
  name_template: "DeploySmith {{.Tag}}"
  prerelease: auto
