version: 2

project_name: smithctl

before:
  hooks:
    - go mod tidy

builds:
  - id: smithctl
    main: ./cmd/smithctl
    binary: smithctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/deploysmith/deploysmith/internal/smithctl/cmd.Version={{.Version}}
      - -X github.com/deploysmith/deploysmith/internal/smithctl/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/deploysmith/deploysmith/internal/smithctl/cmd.BuildTime={{.Date}}

archives:
  - id: smithctl
    name_template: "smithctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/specs/smithctl-spec.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Others'
      order: 999

release:
  github:
    owner: sorenmh
    name: deploysmith
  name_template: "smithctl {{.Tag}}"
  prerelease: auto
